# Generated by Django 4.2.1 on 2023-05-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='mafia.player'),
        ),
    ]
