# Generated by Django 4.2.1 on 2023-05-14 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0003_game_created_at_game_modified_at_player_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mafia.turn'),
            preserve_default=False,
        ),
    ]
