# Generated by Django 4.2.1 on 2023-05-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0004_player_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='turn',
        ),
    ]
